# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a4f323f4a89855237e522c8efdcc66f62b84bac3b07259b6e2411b3a7777d6f5810373465c2dc50e22a334b9bea3b0b56f391b9c584ac1d8059445ea40f85d29

test:
  secret_key_base: 99d5c7cab5fb383f1a1013b157f11eeaa845a72c4a62f23a04d16ba7af5589d56da42b47d557b4114737cf785fd0b44ec8fe8af619c5b66ed44714ca18a16539

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
